name: Run UI and API tests

on:
  push
  
jobs:
  install_dependency:
    runs-on: ubuntu-latest

    steps:
    - name: "step 1"
      run: ls -la
  
  run_test:
    runs-on: ubuntu-latest
    needs: install_dependency
    steps:
    - name: "step 2"
      run: echo "Echo 2"
