name: Run UI and API tests

on:
  push
  
jobs:
  install_dependency:
    runs-on: ubuntu-latest

    steps:
    
    - name: "Скачиваем selenoid"
      run: curl -s https://aerokube.com/cm/bash  | bash
    - name: "Даём права на запуск selenoid"
      run: chmod +x ./cm
    - name: "Запускаем selenoid"
      run: ./cm selenoid start --vnc
    - name: "Запускаем selenoid-ui"
      run: ./cm selenoid-ui start
    - name: "Используем main репозиторий"
      uses: actions/checkout@v1
    - run: cd homeWork7
    - name: "Запускаем тесты"
      run: mvn clean test
